name: README.md Changed

on: 
  push:
    paths:
      - 'README.md'

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to README Authors
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BODY='🤓 @willmcgugan @oleksis @Adilius README.md changed.'
        DISCUSSIONID='MDEwOkRpc2N1c3Npb24zMzI2MjEw'
        gh api graphql -H 'GraphQL-Features: discussions_api' -f body="$BODY" -F discussionId="$DISCUSSIONID" -f query='mutation($body: String!, $discussionId: ID!){addDiscussionComment(input:{body: $body , discussionId: $discussionId}){comment{id}}}'
